name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Install Mocha (if not installed globally)
        run: npm install mocha --save-dev

      - name: Make Mocha executable
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npx mocha test/test.js
